name 'kbe_perl_app'
maintainer 'Kyle Evans'
maintainer_email 'kylebe@gmail.com'
license 'all_rights'
description 'Installs/Configures kbe_perl_app'
long_description 'Installs/Configures kbe_perl_app'
version '0.1.2'

depends 'kbe_role_ubuntu_1604_base'
depends 'kbe_perl'
depends 'kbe_nginx'
